### ISSUE TITLE
Trading Dupe, Allows Duplicating Items With Trading

### ISSUE THREAD

**Issue by Nozemi** [dodian-community/ub3r-monorepo#6]
## Problem Description
It's currently possible to duplicate items using two accounts/clients to trade. Essentially works by accepting the trade, then X-ing out the client window before the trade is processed on the server.

## Reproducing Problem
1. Login to the game with two accounts using two client windows
2. Initiate a trade between the two accounts
3. One account trades the items being duplicated, the other trades nothing
4. Both accounts accept the first trade window 
5. Account that traded items accepts the trade and closes the client window
6. Then very quickly accept the trade on the other account

Following this recipe, the items traded from the account that logged off will now be in both player's inventories.

_Here is a [video reproduction](https://cdn.discordapp.com/attachments/833650170221821972/870049898307936337/6CyuxZRVrh.mp4) of how it works._

**Comment by arch337** [comment]
Potential fix have been implemented. Waiting for the test result.

**Comment by arch337** [comment]
Fixed
